# Where to output .gif
Output demo.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 14
Set Width 1200
Set Height 600

# ---

# Open the TUI
Sleep 500ms
Type "artgg"
Sleep 1s
Enter

# Navigate to build
Sleep 1s
Down
Sleep 500ms
Down
Sleep 500ms
Enter

# Go through build screen
Sleep 1s
Enter
Sleep 1s
Enter
Sleep 1s
Enter
Sleep 1s
Backspace 2
Type "5"
Sleep 500ms
Enter

# Wait for build to finish
Sleep 8s
Enter

# Exit
Sleep 500ms
Down
Sleep 500ms
Enter
Sleep 1s
